// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgykzoewxemickqjnvpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneWt6b2V3eGVtaWNrcWpudnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzAyMDMsImV4cCI6MjA1NjcwNjIwM30.D3RnJXfoSePokX53vUbKpUQUX3tpRGcXqa-HLrQ5h40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);